name: green_finance_platform
description: AI-powered platform for evaluating and optimizing green finance investments
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.3.5
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  supabase_flutter: 2.8.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    
    - .env